name: Build kojo-day Docker image

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - id: kojo-day-version
        run: |
          python -m pip install kojo-fan-art
          echo "version=$(kojo-day --version)" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: environments/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ftnext/kojo-day:${{ steps.kojo-day-version.outputs.version }}
